using System.Globalization;

namespace IndepenDesk;

/// <summary>
/// Basit yerelleştirme: sistem dilini otomatik algılar (tray menüsünden değiştirilebilir,
/// tercih settings.json'da saklanır). Desteklenen diller: en, tr, de, fr, it, ru, zh, ja.
/// </summary>
internal static class L
{
    public static readonly (string Code, string Native)[] Supported =
    {
        ("en", "English"), ("tr", "Türkçe"), ("de", "Deutsch"), ("fr", "Français"),
        ("it", "Italiano"), ("ru", "Русский"), ("zh", "中文"), ("ja", "日本語")
    };

    /// <summary>"auto" veya dil kodu.</summary>
    public static string Override { get; private set; } = "auto";
    private static Dictionary<string, string> _t = null!;

    static L()
    {
        Override = SettingsStore.GetString("language") ?? "auto";
        Apply();
    }

    public static void SetOverride(string codeOrAuto)
    {
        Override = codeOrAuto;
        SettingsStore.SetString("language", Override);
        Apply();
    }

    private static void Apply()
    {
        string code = Override == "auto"
            ? CultureInfo.CurrentUICulture.TwoLetterISOLanguageName
            : Override;
        _t = Tables.TryGetValue(code, out var t) ? t : Tables["en"];
    }

    public static string T(string key) =>
        _t.TryGetValue(key, out var v) ? v : Tables["en"].TryGetValue(key, out var e) ? e : key;

    public static string F(string key, params object[] args) => string.Format(T(key), args);

    private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        ["en"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — independent desktops per monitor",
            ["menu.overview"] = "Overview  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Restore all windows",
            ["menu.help"] = "How to use…",
            ["menu.language"] = "Language",
            ["menu.anim"] = "Switch animation",
            ["menu.anim.fade"] = "Fade (smooth)",
            ["menu.anim.slide"] = "Slide",
            ["menu.anim.off"] = "None (instant)",
            ["menu.lang.auto"] = "System (auto)",
            ["menu.startup"] = "Start with Windows",
            ["menu.update"] = "Check for updates…",
            ["menu.exit"] = "Exit",
            ["msg.hotkeyFail"] = "Some shortcuts could not be registered (another app may be using them): ",
            ["update.title"] = "IndepenDesk update",
            ["update.available"] = "New version {0} is available (you have {1}).\nOpen the download page?",
            ["update.none"] = "You are running the latest version ({0}).",
            ["update.error"] = "Update check failed. Please check your internet connection.",
            ["osd.desktop"] = "Desktop {0}",
            ["osd.sub"] = "Monitor {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — Overview",
            ["ov.legend"] = "⠿  click a window to jump to it   •   drag a window box onto any desktop card   •   drag a card title onto another card to reorder it, or onto another monitor to move the desktop there   •   ✕ closes a desktop   •   click empty space or press Esc: close",
            ["ov.monitor"] = "Monitor {0}",
            ["ov.desktop"] = "⠿   Desktop {0}",
            ["ov.active"] = "ACTIVE",
            ["ov.empty"] = "Empty — drag windows here",
            ["ov.drop"] = "⬇  Drop here",
            ["ov.menu.move"] = "Move to:  Monitor {0}  •  Desktop {1}",
            ["ov.menu.activeSuffix"] = "  (active)",
            ["ov.menu.goto"] = "Go to this window",
            ["ov.tip.window"] = "Click: switch to this desktop and bring the window up  •  Drag onto a desktop card  •  Right-click: move menu",
            ["ov.tip.header"] = "Drag onto another card: left half inserts before it, right half after. A card on another monitor moves the whole desktop there",
            ["ov.tip.add"] = "Create a new desktop on this monitor  •  Drop a window here and it opens on a brand-new desktop  •  Drop a desktop here to move it to the end",
            ["ov.tip.close"] = "Close this desktop — its windows move to Desktop {0}, nothing is lost",
            ["help.title"] = "How to use IndepenDesk",
            ["help.shortcuts.header"] = "Keyboard shortcuts",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   previous / next desktop on the monitor under the mouse (at the end, → creates a new one)\nCtrl+Alt+↑   —   overview: drag && drop windows and desktops (press again to close)\nCtrl+Alt+↓  /  Ctrl+Alt+Shift+↓   —   close the overview\nCtrl+Alt+1..9   —   jump to the desktop with that global number\nCtrl+Alt+Shift+← / →   —   move the active window to the adjacent desktop and follow it",
            ["help.touchpad.header"] = "Touchpad setup (overrides the Windows default)",
            ["help.touchpad.body"] = "1.  Open Settings → Bluetooth && devices → Touchpad → Advanced gestures.\n2.  Under the four-finger gestures pick \"Custom shortcut\" for each direction and record:\n      swipe left → Ctrl+Alt+←        swipe right → Ctrl+Alt+→        swipe up → Ctrl+Alt+↑\n3.  Recording a custom shortcut automatically replaces the Windows default\n      (the global desktop switch), so only the monitor under your cursor will switch.\n4.  Closing the overview: click any empty space in it, or press Esc.\n      Gestures cannot close it: while the overview is on top, Windows stops delivering the\n      shortcuts assigned to touchpad gestures, so a second swipe never reaches the app.\n      Ctrl+Alt+↑ from the keyboard closes it as well.",
            ["help.touchpad.open"] = "Open touchpad settings",
            ["help.demo.header"] = "Gestures",
            ["help.demo.swipeLR"] = "4-finger swipe left / right  →  switch desktop on the monitor under the cursor",
            ["help.demo.swipeUp"] = "4-finger swipe up  →  overview",
            ["help.close"] = "Close",
        },
        ["tr"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — monitör başına bağımsız masaüstleri",
            ["menu.overview"] = "Genel bakış  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Tüm pencereleri geri getir",
            ["menu.help"] = "Nasıl kullanılır…",
            ["menu.language"] = "Dil",
            ["menu.lang.auto"] = "Sistem (otomatik)",
            ["menu.startup"] = "Windows ile başlat",
            ["menu.update"] = "Güncellemeleri denetle…",
            ["menu.exit"] = "Çıkış",
            ["msg.hotkeyFail"] = "Bazı kısayollar kaydedilemedi (başka bir uygulama kullanıyor olabilir): ",
            ["update.title"] = "IndepenDesk güncelleme",
            ["update.available"] = "Yeni sürüm {0} yayınlandı (sizdeki: {1}).\nİndirme sayfası açılsın mı?",
            ["update.none"] = "En güncel sürümü kullanıyorsunuz ({0}).",
            ["update.error"] = "Güncelleme denetimi başarısız. İnternet bağlantınızı kontrol edin.",
            ["osd.desktop"] = "Masaüstü {0}",
            ["osd.sub"] = "Monitör {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — Genel Bakış",
            ["ov.legend"] = "⠿  pencere kutucuğunu istediğiniz masaüstü kartına sürükleyin   •   kart başlığını başka monitör satırına sürükleyin   •   pencereye sağ tık: taşıma menüsü   •   karta tıkla: geç   •   Esc: kapat",
            ["ov.monitor"] = "Monitör {0}",
            ["ov.desktop"] = "⠿   Masaüstü {0}",
            ["ov.active"] = "AKTİF",
            ["ov.empty"] = "Boş — pencereleri buraya sürükleyin",
            ["ov.more"] = "… ve {0} pencere daha",
            ["ov.drop"] = "⬇  Buraya bırak",
            ["ov.menu.move"] = "Taşı:  Monitör {0}  •  Masaüstü {1}",
            ["ov.menu.activeSuffix"] = "  (aktif)",
            ["ov.menu.goto"] = "Bu pencereye git",
            ["ov.tip.window"] = "Bir masaüstü kartına sürükleyin  •  Sağ tık: taşıma menüsü",
            ["ov.tip.header"] = "Başka monitörün satırına sürükleyin: masaüstü komple taşınır",
            ["ov.tip.add"] = "Bu monitörde yeni masaüstü oluştur ve ona geç",
            ["help.title"] = "IndepenDesk nasıl kullanılır",
            ["help.shortcuts.header"] = "Klavye kısayolları",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   farenin olduğu monitörde önceki / sonraki masaüstü (sonda → yenisini oluşturur)\nCtrl+Alt+↑   —   genel bakış: pencereleri ve masaüstlerini sürükle-bırak\nCtrl+Alt+1..9   —   global numaralı masaüstüne git\nCtrl+Alt+Shift+← / →   —   aktif pencereyi bitişik masaüstüne taşı ve oraya geç",
            ["help.touchpad.header"] = "Touchpad kurulumu (Windows varsayılanını ezer)",
            ["help.touchpad.body"] = "1.  Ayarlar → Bluetooth ve cihazlar → Dokunmatik yüzey → Gelişmiş hareketler'i açın.\n2.  Dört parmak hareketlerinde her yön için \"Özel kısayol\" seçip şunları kaydedin:\n      sola çekme → Ctrl+Alt+←        sağa çekme → Ctrl+Alt+→        yukarı çekme → Ctrl+Alt+↑\n3.  Özel kısayol kaydettiğiniz anda Windows varsayılanı (tüm ekranları birden kaydıran\n      global geçiş) otomatik olarak devre dışı kalır; yalnızca imlecin olduğu monitör değişir.",
            ["help.touchpad.open"] = "Dokunmatik yüzey ayarlarını aç",
            ["help.demo.header"] = "Hareketler",
            ["help.demo.swipeLR"] = "4 parmak sola / sağa kaydırma  →  imlecin olduğu monitörde masaüstü değiştir",
            ["help.demo.swipeUp"] = "4 parmak yukarı kaydırma  →  genel bakış",
            ["help.close"] = "Kapat",
        },
        ["de"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — unabhängige Desktops pro Monitor",
            ["menu.overview"] = "Übersicht  (Strg+Alt+↑)",
            ["menu.restore"] = "Alle Fenster wiederherstellen",
            ["menu.help"] = "Bedienungsanleitung…",
            ["menu.language"] = "Sprache",
            ["menu.lang.auto"] = "System (automatisch)",
            ["menu.startup"] = "Mit Windows starten",
            ["menu.update"] = "Nach Updates suchen…",
            ["menu.exit"] = "Beenden",
            ["msg.hotkeyFail"] = "Einige Tastenkürzel konnten nicht registriert werden (evtl. von einer anderen App belegt): ",
            ["update.title"] = "IndepenDesk-Update",
            ["update.available"] = "Neue Version {0} ist verfügbar (installiert: {1}).\nDownload-Seite öffnen?",
            ["update.none"] = "Sie verwenden bereits die neueste Version ({0}).",
            ["update.error"] = "Update-Prüfung fehlgeschlagen. Bitte Internetverbindung prüfen.",
            ["osd.desktop"] = "Desktop {0}",
            ["osd.sub"] = "Monitor {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — Übersicht",
            ["ov.legend"] = "⠿  Fensterkästchen auf eine Desktop-Karte ziehen   •   Kartentitel auf eine andere Monitorzeile ziehen   •   Rechtsklick auf Fenster: Verschieben-Menü   •   Karte anklicken: wechseln   •   Esc: schließen",
            ["ov.monitor"] = "Monitor {0}",
            ["ov.desktop"] = "⠿   Desktop {0}",
            ["ov.active"] = "AKTIV",
            ["ov.empty"] = "Leer — Fenster hierher ziehen",
            ["ov.more"] = "… und {0} weitere Fenster",
            ["ov.drop"] = "⬇  Hier ablegen",
            ["ov.menu.move"] = "Verschieben:  Monitor {0}  •  Desktop {1}",
            ["ov.menu.activeSuffix"] = "  (aktiv)",
            ["ov.menu.goto"] = "Zu diesem Fenster wechseln",
            ["ov.tip.window"] = "Auf eine Desktop-Karte ziehen  •  Rechtsklick: Verschieben-Menü",
            ["ov.tip.header"] = "Auf eine andere Monitorzeile ziehen, um den ganzen Desktop zu verschieben",
            ["ov.tip.add"] = "Neuen Desktop auf diesem Monitor erstellen und dorthin wechseln",
            ["help.title"] = "IndepenDesk-Bedienungsanleitung",
            ["help.shortcuts.header"] = "Tastenkürzel",
            ["help.shortcuts.body"] = "Strg+Alt+← / →   —   vorheriger / nächster Desktop auf dem Monitor unter der Maus (am Ende erstellt → einen neuen)\nStrg+Alt+↑   —   Übersicht: Fenster und Desktops per Drag && Drop verschieben\nStrg+Alt+1..9   —   zum Desktop mit dieser globalen Nummer springen\nStrg+Alt+Umschalt+← / →   —   aktives Fenster auf den Nachbar-Desktop verschieben",
            ["help.touchpad.header"] = "Touchpad einrichten (überschreibt den Windows-Standard)",
            ["help.touchpad.body"] = "1.  Einstellungen → Bluetooth && Geräte → Touchpad → Erweiterte Gesten öffnen.\n2.  Bei den Vier-Finger-Gesten für jede Richtung \"Benutzerdefinierte Tastenkombination\" wählen:\n      nach links → Strg+Alt+←        nach rechts → Strg+Alt+→        nach oben → Strg+Alt+↑\n3.  Eine benutzerdefinierte Tastenkombination ersetzt automatisch den Windows-Standard\n      (globaler Desktopwechsel); es wechselt nur der Monitor unter dem Cursor.",
            ["help.touchpad.open"] = "Touchpad-Einstellungen öffnen",
            ["help.demo.header"] = "Gesten",
            ["help.demo.swipeLR"] = "Mit 4 Fingern nach links / rechts wischen  →  Desktop auf dem Monitor unter dem Cursor wechseln",
            ["help.demo.swipeUp"] = "Mit 4 Fingern nach oben wischen  →  Übersicht",
            ["help.close"] = "Schließen",
        },
        ["fr"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — bureaux indépendants par moniteur",
            ["menu.overview"] = "Vue d'ensemble  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Restaurer toutes les fenêtres",
            ["menu.help"] = "Mode d'emploi…",
            ["menu.language"] = "Langue",
            ["menu.lang.auto"] = "Système (auto)",
            ["menu.startup"] = "Lancer au démarrage de Windows",
            ["menu.update"] = "Rechercher des mises à jour…",
            ["menu.exit"] = "Quitter",
            ["msg.hotkeyFail"] = "Certains raccourcis n'ont pas pu être enregistrés (peut-être utilisés par une autre application) : ",
            ["update.title"] = "Mise à jour d'IndepenDesk",
            ["update.available"] = "La nouvelle version {0} est disponible (vous avez {1}).\nOuvrir la page de téléchargement ?",
            ["update.none"] = "Vous utilisez déjà la dernière version ({0}).",
            ["update.error"] = "Échec de la vérification des mises à jour. Vérifiez votre connexion Internet.",
            ["osd.desktop"] = "Bureau {0}",
            ["osd.sub"] = "Moniteur {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — Vue d'ensemble",
            ["ov.legend"] = "⠿  faites glisser une fenêtre sur une carte de bureau   •   faites glisser le titre d'une carte sur une autre ligne de moniteur   •   clic droit sur une fenêtre : menu de déplacement   •   clic sur une carte : basculer   •   Échap : fermer",
            ["ov.monitor"] = "Moniteur {0}",
            ["ov.desktop"] = "⠿   Bureau {0}",
            ["ov.active"] = "ACTIF",
            ["ov.empty"] = "Vide — glissez des fenêtres ici",
            ["ov.more"] = "… et {0} autres fenêtres",
            ["ov.drop"] = "⬇  Déposer ici",
            ["ov.menu.move"] = "Déplacer vers :  Moniteur {0}  •  Bureau {1}",
            ["ov.menu.activeSuffix"] = "  (actif)",
            ["ov.menu.goto"] = "Aller à cette fenêtre",
            ["ov.tip.window"] = "Glissez sur une carte de bureau  •  Clic droit : menu de déplacement",
            ["ov.tip.header"] = "Glissez sur une autre ligne de moniteur pour déplacer tout le bureau",
            ["ov.tip.add"] = "Créer un nouveau bureau sur ce moniteur et y basculer",
            ["help.title"] = "Mode d'emploi d'IndepenDesk",
            ["help.shortcuts.header"] = "Raccourcis clavier",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   bureau précédent / suivant sur le moniteur sous la souris (à la fin, → en crée un nouveau)\nCtrl+Alt+↑   —   vue d'ensemble : glisser-déposer fenêtres et bureaux\nCtrl+Alt+1..9   —   aller au bureau portant ce numéro global\nCtrl+Alt+Maj+← / →   —   déplacer la fenêtre active vers le bureau adjacent",
            ["help.touchpad.header"] = "Configuration du pavé tactile (remplace le comportement Windows)",
            ["help.touchpad.body"] = "1.  Ouvrez Paramètres → Bluetooth et appareils → Pavé tactile → Mouvements avancés.\n2.  Pour les mouvements à quatre doigts, choisissez « Raccourci personnalisé » pour chaque direction :\n      vers la gauche → Ctrl+Alt+←        vers la droite → Ctrl+Alt+→        vers le haut → Ctrl+Alt+↑\n3.  Un raccourci personnalisé remplace automatiquement le comportement Windows par défaut\n      (changement global de bureau) ; seul le moniteur sous le curseur bascule.",
            ["help.touchpad.open"] = "Ouvrir les paramètres du pavé tactile",
            ["help.demo.header"] = "Gestes",
            ["help.demo.swipeLR"] = "Balayage à 4 doigts vers la gauche / droite  →  changer de bureau sur le moniteur sous le curseur",
            ["help.demo.swipeUp"] = "Balayage à 4 doigts vers le haut  →  vue d'ensemble",
            ["help.close"] = "Fermer",
        },
        ["it"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — desktop indipendenti per ogni monitor",
            ["menu.overview"] = "Panoramica  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Ripristina tutte le finestre",
            ["menu.help"] = "Come si usa…",
            ["menu.language"] = "Lingua",
            ["menu.lang.auto"] = "Sistema (auto)",
            ["menu.startup"] = "Avvia con Windows",
            ["menu.update"] = "Controlla aggiornamenti…",
            ["menu.exit"] = "Esci",
            ["msg.hotkeyFail"] = "Alcune scorciatoie non sono state registrate (forse usate da un'altra app): ",
            ["update.title"] = "Aggiornamento IndepenDesk",
            ["update.available"] = "È disponibile la nuova versione {0} (installata: {1}).\nAprire la pagina di download?",
            ["update.none"] = "Stai già usando l'ultima versione ({0}).",
            ["update.error"] = "Controllo aggiornamenti non riuscito. Verifica la connessione Internet.",
            ["osd.desktop"] = "Desktop {0}",
            ["osd.sub"] = "Monitor {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — Panoramica",
            ["ov.legend"] = "⠿  trascina una finestra su una scheda desktop   •   trascina il titolo di una scheda su un'altra riga di monitor   •   clic destro su una finestra: menu di spostamento   •   clic su una scheda: passa   •   Esc: chiudi",
            ["ov.monitor"] = "Monitor {0}",
            ["ov.desktop"] = "⠿   Desktop {0}",
            ["ov.active"] = "ATTIVO",
            ["ov.empty"] = "Vuoto — trascina qui le finestre",
            ["ov.more"] = "… e altre {0} finestre",
            ["ov.drop"] = "⬇  Rilascia qui",
            ["ov.menu.move"] = "Sposta in:  Monitor {0}  •  Desktop {1}",
            ["ov.menu.activeSuffix"] = "  (attivo)",
            ["ov.menu.goto"] = "Vai a questa finestra",
            ["ov.tip.window"] = "Trascina su una scheda desktop  •  Clic destro: menu di spostamento",
            ["ov.tip.header"] = "Trascina su un'altra riga di monitor per spostare l'intero desktop",
            ["ov.tip.add"] = "Crea un nuovo desktop su questo monitor e passaci",
            ["help.title"] = "Come si usa IndepenDesk",
            ["help.shortcuts.header"] = "Scorciatoie da tastiera",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   desktop precedente / successivo sul monitor sotto il mouse (alla fine, → ne crea uno nuovo)\nCtrl+Alt+↑   —   panoramica: trascina finestre e desktop\nCtrl+Alt+1..9   —   vai al desktop con quel numero globale\nCtrl+Alt+Maiusc+← / →   —   sposta la finestra attiva sul desktop adiacente",
            ["help.touchpad.header"] = "Configurazione del touchpad (sostituisce il comportamento di Windows)",
            ["help.touchpad.body"] = "1.  Apri Impostazioni → Bluetooth e dispositivi → Touchpad → Movimenti avanzati.\n2.  Nei movimenti a quattro dita scegli \"Collegamento personalizzato\" per ogni direzione:\n      scorri a sinistra → Ctrl+Alt+←        scorri a destra → Ctrl+Alt+→        scorri in alto → Ctrl+Alt+↑\n3.  Un collegamento personalizzato sostituisce automaticamente il comportamento predefinito\n      di Windows (cambio globale); cambia solo il monitor sotto il cursore.",
            ["help.touchpad.open"] = "Apri impostazioni touchpad",
            ["help.demo.header"] = "Gesti",
            ["help.demo.swipeLR"] = "Scorrimento a 4 dita a sinistra / destra  →  cambia desktop sul monitor sotto il cursore",
            ["help.demo.swipeUp"] = "Scorrimento a 4 dita in alto  →  panoramica",
            ["help.close"] = "Chiudi",
        },
        ["ru"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — независимые рабочие столы для каждого монитора",
            ["menu.overview"] = "Обзор  (Ctrl+Alt+↑)",
            ["menu.restore"] = "Восстановить все окна",
            ["menu.help"] = "Как пользоваться…",
            ["menu.language"] = "Язык",
            ["menu.anim"] = "Анимация перехода",
            ["menu.anim.fade"] = "Затухание (плавно)",
            ["menu.anim.slide"] = "Сдвиг",
            ["menu.anim.off"] = "Без анимации",
            ["menu.lang.auto"] = "Системный (авто)",
            ["menu.startup"] = "Запускать вместе с Windows",
            ["menu.update"] = "Проверить обновления…",
            ["menu.exit"] = "Выход",
            ["msg.hotkeyFail"] = "Не удалось зарегистрировать некоторые сочетания клавиш (возможно, заняты другим приложением): ",
            ["update.title"] = "Обновление IndepenDesk",
            ["update.available"] = "Доступна новая версия {0} (у вас {1}).\nОткрыть страницу загрузки?",
            ["update.none"] = "У вас уже последняя версия ({0}).",
            ["update.error"] = "Не удалось проверить обновления. Проверьте подключение к Интернету.",
            ["osd.desktop"] = "Рабочий стол {0}",
            ["osd.sub"] = "Монитор {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — Обзор",
            ["ov.legend"] = "⠿  клик по программе — перейти к ней   •   перетащите окно на карточку рабочего стола   •   перетащите заголовок карточки на другую карточку, чтобы изменить порядок или перенести стол на другой монитор   •   ✕ закрывает рабочий стол   •   клик по пустому месту или Esc: закрыть панель",
            ["ov.monitor"] = "Монитор {0}",
            ["ov.desktop"] = "⠿   Рабочий стол {0}",
            ["ov.active"] = "АКТИВЕН",
            ["ov.empty"] = "Пусто — перетащите окна сюда",
            ["ov.drop"] = "⬇  Отпустите здесь",
            ["ov.menu.move"] = "Переместить:  Монитор {0}  •  Рабочий стол {1}",
            ["ov.menu.activeSuffix"] = "  (активен)",
            ["ov.menu.goto"] = "Перейти к этому окну",
            ["ov.tip.window"] = "Клик: перейти на этот рабочий стол и раскрыть окно  •  Перетащите на карточку  •  Правый клик: меню перемещения",
            ["ov.tip.header"] = "Перетащите на другую карточку: слева от неё — вставить перед, справа — после. Карточка другого монитора переносит весь рабочий стол туда",
            ["ov.tip.add"] = "Создать новый рабочий стол на этом мониторе  •  Отпустите здесь окно — оно откроется на новом столе  •  Отпустите рабочий стол, чтобы перенести его в конец",
            ["ov.tip.close"] = "Закрыть этот рабочий стол — его окна переедут на Рабочий стол {0}, ничего не потеряется",
            ["help.title"] = "Как пользоваться IndepenDesk",
            ["help.shortcuts.header"] = "Сочетания клавиш",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   предыдущий / следующий рабочий стол на мониторе под курсором (в конце → создаёт новый)\nCtrl+Alt+↑   —   обзор: перетаскивание окон и рабочих столов (повторно — закрыть)\nCtrl+Alt+↓  /  Ctrl+Alt+Shift+↓   —   закрыть обзор\nCtrl+Alt+1..9   —   перейти к рабочему столу с этим глобальным номером\nCtrl+Alt+Shift+← / →   —   переместить активное окно на соседний рабочий стол",
            ["help.touchpad.header"] = "Настройка сенсорной панели (заменяет стандартное поведение Windows)",
            ["help.touchpad.body"] = "1.  Откройте Параметры → Bluetooth и устройства → Сенсорная панель → Дополнительные жесты.\n2.  Для жестов четырьмя пальцами выберите «Настраиваемое сочетание клавиш» для каждого направления:\n      влево → Ctrl+Alt+←        вправо → Ctrl+Alt+→        вверх → Ctrl+Alt+↑\n3.  Настраиваемое сочетание автоматически заменяет стандартное поведение Windows\n      (глобальное переключение); переключается только монитор под курсором.\n4.  Закрыть обзор: клик по любому пустому месту в нём или Esc.\n      Жестом его закрыть нельзя: пока обзор поверх всего, Windows перестаёт доставлять\n      сочетания, назначенные на жесты тачпада, и второй свайп до программы не доходит.\n      С клавиатуры закрывает также Ctrl+Alt+↑.",
            ["help.touchpad.open"] = "Открыть настройки сенсорной панели",
            ["help.demo.header"] = "Жесты",
            ["help.demo.swipeLR"] = "Смахивание 4 пальцами влево / вправо  →  сменить рабочий стол на мониторе под курсором",
            ["help.demo.swipeUp"] = "Смахивание 4 пальцами вверх  →  обзор",
            ["help.close"] = "Закрыть",
        },
        ["zh"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — 每个显示器独立的虚拟桌面",
            ["menu.overview"] = "总览  (Ctrl+Alt+↑)",
            ["menu.restore"] = "恢复所有窗口",
            ["menu.help"] = "使用说明…",
            ["menu.language"] = "语言",
            ["menu.lang.auto"] = "系统（自动）",
            ["menu.startup"] = "开机自动启动",
            ["menu.update"] = "检查更新…",
            ["menu.exit"] = "退出",
            ["msg.hotkeyFail"] = "部分快捷键注册失败（可能被其他应用占用）：",
            ["update.title"] = "IndepenDesk 更新",
            ["update.available"] = "发现新版本 {0}（当前版本 {1}）。\n是否打开下载页面？",
            ["update.none"] = "您已在使用最新版本（{0}）。",
            ["update.error"] = "检查更新失败，请检查网络连接。",
            ["osd.desktop"] = "桌面 {0}",
            ["osd.sub"] = "显示器 {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — 总览",
            ["ov.legend"] = "⠿  将窗口拖到任意桌面卡片   •   将卡片标题拖到其他显示器行   •   右键窗口：移动菜单   •   点击卡片：切换   •   Esc：关闭",
            ["ov.monitor"] = "显示器 {0}",
            ["ov.desktop"] = "⠿   桌面 {0}",
            ["ov.active"] = "当前",
            ["ov.empty"] = "空 — 将窗口拖到这里",
            ["ov.more"] = "… 还有 {0} 个窗口",
            ["ov.drop"] = "⬇  放到这里",
            ["ov.menu.move"] = "移动到：显示器 {0}  •  桌面 {1}",
            ["ov.menu.activeSuffix"] = "（当前）",
            ["ov.menu.goto"] = "转到此窗口",
            ["ov.tip.window"] = "拖到桌面卡片上  •  右键：移动菜单",
            ["ov.tip.header"] = "拖到其他显示器行可整体移动该桌面",
            ["ov.tip.add"] = "在此显示器上新建桌面并切换过去",
            ["help.title"] = "IndepenDesk 使用说明",
            ["help.shortcuts.header"] = "键盘快捷键",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   切换鼠标所在显示器的上一个 / 下一个桌面（在末尾按 → 新建桌面）\nCtrl+Alt+↑   —   总览：拖放窗口和桌面\nCtrl+Alt+1..9   —   跳转到对应全局编号的桌面\nCtrl+Alt+Shift+← / →   —   将当前窗口移到相邻桌面并跟随",
            ["help.touchpad.header"] = "触摸板设置（覆盖 Windows 默认行为）",
            ["help.touchpad.body"] = "1.  打开 设置 → 蓝牙和其他设备 → 触摸板 → 高级手势。\n2.  在四指手势中为每个方向选择\"自定义快捷方式\"并录制：\n      向左滑动 → Ctrl+Alt+←        向右滑动 → Ctrl+Alt+→        向上滑动 → Ctrl+Alt+↑\n3.  录制自定义快捷方式后会自动替换 Windows 默认行为（全局桌面切换），\n      只有光标所在的显示器会切换。",
            ["help.touchpad.open"] = "打开触摸板设置",
            ["help.demo.header"] = "手势",
            ["help.demo.swipeLR"] = "四指左右滑动  →  切换光标所在显示器的桌面",
            ["help.demo.swipeUp"] = "四指上滑  →  总览",
            ["help.close"] = "关闭",
        },
        ["ja"] = new()
        {
            ["tray.tooltip"] = "IndepenDesk — モニターごとに独立したデスクトップ",
            ["menu.overview"] = "オーバービュー  (Ctrl+Alt+↑)",
            ["menu.restore"] = "すべてのウィンドウを復元",
            ["menu.help"] = "使い方…",
            ["menu.language"] = "言語",
            ["menu.lang.auto"] = "システム（自動）",
            ["menu.startup"] = "Windows 起動時に実行",
            ["menu.update"] = "更新を確認…",
            ["menu.exit"] = "終了",
            ["msg.hotkeyFail"] = "一部のショートカットを登録できませんでした（他のアプリが使用中の可能性）：",
            ["update.title"] = "IndepenDesk の更新",
            ["update.available"] = "新しいバージョン {0} が利用可能です（現在: {1}）。\nダウンロードページを開きますか？",
            ["update.none"] = "最新バージョン（{0}）をご利用中です。",
            ["update.error"] = "更新の確認に失敗しました。インターネット接続をご確認ください。",
            ["osd.desktop"] = "デスクトップ {0}",
            ["osd.sub"] = "モニター {0}  •  {1} / {2}",
            ["ov.title"] = "IndepenDesk — オーバービュー",
            ["ov.legend"] = "⠿  ウィンドウをデスクトップカードへドラッグ   •   カードのタイトルを別のモニター行へドラッグ   •   ウィンドウを右クリック：移動メニュー   •   カードをクリック：切り替え   •   Esc：閉じる",
            ["ov.monitor"] = "モニター {0}",
            ["ov.desktop"] = "⠿   デスクトップ {0}",
            ["ov.active"] = "使用中",
            ["ov.empty"] = "空 — ここにウィンドウをドラッグ",
            ["ov.more"] = "… 他 {0} 個のウィンドウ",
            ["ov.drop"] = "⬇  ここにドロップ",
            ["ov.menu.move"] = "移動:  モニター {0}  •  デスクトップ {1}",
            ["ov.menu.activeSuffix"] = "（使用中）",
            ["ov.menu.goto"] = "このウィンドウへ移動",
            ["ov.tip.window"] = "デスクトップカードへドラッグ  •  右クリック：移動メニュー",
            ["ov.tip.header"] = "別のモニター行へドラッグするとデスクトップごと移動します",
            ["ov.tip.add"] = "このモニターに新しいデスクトップを作成して切り替え",
            ["help.title"] = "IndepenDesk の使い方",
            ["help.shortcuts.header"] = "キーボードショートカット",
            ["help.shortcuts.body"] = "Ctrl+Alt+← / →   —   マウスのあるモニターで前 / 次のデスクトップへ（末尾で → は新規作成）\nCtrl+Alt+↑   —   オーバービュー：ウィンドウとデスクトップをドラッグ＆ドロップ\nCtrl+Alt+1..9   —   そのグローバル番号のデスクトップへ移動\nCtrl+Alt+Shift+← / →   —   アクティブウィンドウを隣のデスクトップへ移動",
            ["help.touchpad.header"] = "タッチパッド設定（Windows の既定動作を上書き）",
            ["help.touchpad.body"] = "1.  設定 → Bluetooth とデバイス → タッチパッド → 高度なジェスチャ を開きます。\n2.  4 本指ジェスチャの各方向で「カスタムショートカット」を選んで記録します：\n      左にスワイプ → Ctrl+Alt+←        右にスワイプ → Ctrl+Alt+→        上にスワイプ → Ctrl+Alt+↑\n3.  カスタムショートカットを記録すると Windows の既定動作（全モニター一括切り替え）は\n      自動的に無効になり、カーソルのあるモニターだけが切り替わります。",
            ["help.touchpad.open"] = "タッチパッド設定を開く",
            ["help.demo.header"] = "ジェスチャ",
            ["help.demo.swipeLR"] = "4 本指で左右にスワイプ  →  カーソルのあるモニターのデスクトップを切り替え",
            ["help.demo.swipeUp"] = "4 本指で上にスワイプ  →  オーバービュー",
            ["help.close"] = "閉じる",
        },
    };
}
